# Generated by Django 3.0.7 on 2020-12-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geo_tagging',
            name='city',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='geo_tagging',
            name='district',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
