# Generated by Django 3.0.7 on 2020-12-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0002_auto_20201229_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geo_tagging',
            name='dpr_no',
            field=models.IntegerField(null=True),
        ),
    ]
