# Generated by Django 3.0.7 on 2020-12-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0003_auto_20201229_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='geo_tagging',
            name='balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='geo_tagging',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
