# Generated by Django 3.0.7 on 2020-12-30 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dbms', '0004_auto_20201229_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='FUND_DETAILS',
            fields=[
                ('fn', models.IntegerField(null=True)),
                ('sn', models.IntegerField(null=True)),
                ('tn', models.IntegerField(null=True)),
                ('fu', models.IntegerField(null=True)),
                ('su', models.IntegerField(null=True)),
                ('tu', models.IntegerField(null=True)),
                ('fund_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
