# Generated by Django 3.0.7 on 2021-01-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0006_auto_20210111_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15, null=True)),
                ('phonenumber', models.IntegerField(null=True)),
                ('address', models.CharField(default='', max_length=15, null=True)),
            ],
            options={
                'permissions': (('is_admin', 'Can view records'),),
            },
        ),
    ]
