# Generated by Django 3.0.7 on 2021-01-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0009_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
