# Generated by Django 3.0.7 on 2021-01-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0011_auto_20210114_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='usn',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
