# Generated by Django 3.0.7 on 2021-01-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0012_student_usn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='phonenumber',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phonenumber',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='phonenumber',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
