# Generated by Django 3.0.7 on 2021-06-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0014_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='image',
        ),
    ]
