# Generated by Django 3.0.7 on 2021-06-25 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0015_remove_img_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
