# Generated by Django 3.0.7 on 2021-07-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0018_enroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
