# Generated by Django 3.0.7 on 2021-07-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0019_auto_20210703_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(upload_to='videos/%y'),
        ),
    ]
